### ISSUE TITLE
KeyError: 'gac+20'

### ISSUE THREAD

**Issue by rana2704** [NickSwainston/pulsar_spectra#66] opened 2022-11-19 10:39 UTC
I am trying to make plots for my pulsars sample, BUT just tried simple example (mentioned in documentation) and experiencing following error

**"KeyError: 'gac+20'"**

I tried to fix the problem by running following command line as suggested in FAQS in documentation.

''import psrqpy
psrqpy.get_references(updaterefcache=True)
psrqpy.QueryATNF(checkupdate=True)''

BUT nothing seems to be work.
Any suggestions?

**Comment by NickSwainston** [comment] 2022-11-19 11:10
I would recommend uninstalling and reinstalling `psrqpy` like so

```
pip uninstall psrqpy
pip install psrqpy
```

And try again. Let me know if that solves the issue

**Comment by harvey0908** [comment] 2022-11-21 09:47
import psrqpy
psrqpy.get_references(updaterefcache=True)
psrqpy.QueryATNF(checkupdate=True)
from pulsar_spectra.catalogue import collect_catalogue_fluxes
from pulsar_spectra.spectral_fit import find_best_spectral_fit

cat_dict = collect_catalogue_fluxes()
pulsar = 'J0332+5434'
freqs, bands, fluxs, flux_errs, refs = cat_dict[pulsar]
best_model_name, iminuit_result, fit_info, p_best, p_category = find_best_spectral_fit(pulsar, freqs, bands, fluxs, flux_errs, refs, plot_best=True)

**Comment by NickSwainston** [comment] 2022-11-22 01:56
I get the same bug as you both if I install the software on a new machine or in a docker image, and I can't fix it either, so I've made a temporary fix. To install the fix, `git clone` the pulsar_spectra repo, then install the fix branch using
```
git pull
git checkout psrqpy_temp_fix
pip install .
```
Basically, this branch won't specify the ATNF version, which will be fine for now. I'll start working on a better fix.

**Comment by harvey0908** [comment] 2022-11-22 05:31
Thanks, I'll tray again.

**Comment by NickSwainston** [comment] 2022-11-23 03:42
I have fixed the error properly, so you can install the fix by installing the latest version
```
pip install pulsar_spectra==2.0.1
```

**Comment by harvey0908** [comment] 2022-11-23 13:07
It can work now, but there seems to be something wrong with the identification of references.

**Comment by NickSwainston** [comment] 2022-11-24 01:42
What do you mean? Can you send an error code or an plot with the issue?

**Comment by harvey0908** [comment] 2022-11-24 02:21
![J0034-0534_double_turn_over_spectrum_fit](https://user-images.githubusercontent.com/87842773/203679690-97b992ed-0292-4ee6-bfe4-d86a21629f7d.png)

**Comment by harvey0908** [comment] 2022-11-24 02:26
I'll try to find the cause because I'm not sure if it's my own fault

**Comment by harvey0908** [comment] 2022-11-27 11:39
I added a piece of code in it and the problem seems to be solved。
【refs= [os.path.basename(i) for i in cat_list[pulsar][-1]]】

**Comment by NickSwainston** [comment] 2022-11-28 01:28
I just fixed that error so you will no longer have to do your fix if you install it with:
```
git checkout main
git pull
pip install .
```
Sorry for all these bugs, it is a new repository and I didn't test it on Windows

**Comment by harvey0908** [comment] 2023-01-30 05:44
hi，I get some results ,but it seems not right.I'm not sure what caused it and how can I modify it next.Thanks


![J0030+0451](https://user-images.githubusercontent.com/87842773/215396491-483bf32e-df0f-4d78-a8ae-e325ae1bdd45.png)

**Comment by harvey0908** [comment] 2023-01-30 05:52
hi，I get some results ,but it seems not right.I'm not sure what caused it and how can I modify it next.Thanks
![J0030+0451](https://user-images.githubusercontent.com/87842773/215397804-fdae4d54-eb0f-4e78-839e-8cc8e8e05ac5.png)

**Comment by NickSwainston** [comment] 2023-01-30 05:58
Looks like fit is off by a factor of 100. Can you send me the code you used to create this?

**Comment by harvey0908** [comment] 2023-01-30 06:53
here is the main code
![_20230130145308](https://user-images.githubusercontent.com/87842773/215407862-ce0d4cc4-4629-4ee9-a2f9-9216242a03db.png)

**Comment by NickSwainston** [comment] 2023-01-30 08:17
This is what I get with the most recent version of `pulsar-spectra` :

```
from pulsar_spectra.catalogue import collect_catalogue_fluxes
from pulsar_spectra.spectral_fit import find_best_spectral_fit
import matplotlib.pyplot as plt

fig, ax1 = plt.subplots(1,1,dpi=300)
cat_list = collect_catalogue_fluxes()
pulsar = 'J0030+0451'
freqs, bands, fluxs, flux_errs, refs = cat_list[pulsar]
find_best_spectral_fit(
    pulsar, freqs, bands, fluxs, flux_errs, refs,
    plot_best=True, axis=ax1,alternate_style=True
)
ax1.set_title('PSR '+pulsar)
if min(freqs) < 100:
    xmin = 10
else:
    xmin = 100
if max(freqs) > 10000:
    xmax = 100000
elif 1000 < max(freqs) < 10000:
    xmax = 10000
else:
    xmax = 1000
ax1.set_xlim(xmin, xmax)
fig.savefig('test.png')
```
![test](https://user-images.githubusercontent.com/18390846/215423185-21d78fde-9660-4537-b4a2-cbd08f23e8ca.png)

It appears you have added two new papers to the catalogue, so it may be an issue with their data. If you make a pull request with the data you have added I can review it to see if there are any issues.

**Comment by harvey0908** [comment] 2023-02-01 05:31
Thanks for your suggestion.I checked the data and it seems no issues.I'm not familiar with the github.So I put the added literature data on my homepage named catalogue_temp.

**Comment by NickSwainston** [comment] 2023-02-01 07:13
I had a look, and I'm impressed by the large number of papers you have added! Because you have put in so much work, I want you to get credit for your effort (GitHub tracks code contributions, so it's like being an author on a paper). 

I've [updated the documentation](https://pulsar-spectra.readthedocs.io/en/latest/catalogue.html#uploading-the-new-catalogue-to-github) to make it clearer how to add the catalogue files to GitHub. I hope this is clear enough, but if you have any more questions, feel free to ask me. 

I hope it won't be too much work for you, or at least it will be worth it because then we can work from the same code, which will make it easier to find any errors/bugs

**Comment by NickSwainston** [comment] 2023-02-12 02:58
Fixed in #74 so your plot should now look like this

![test](https://user-images.githubusercontent.com/18390846/218290414-97da23fe-e8b2-43a3-bbea-0b3099c135b6.png)

**Comment by harvey0908** [comment] 2023-02-12 10:53
Yeah, I got the same result. My next job is to determine their spectral index （4 points and more ).

**Comment by Ramrhrh** [comment] 2023-04-04 08:21
hi ,it seems that the log_parabolic_spectrum model cann't be adopted.

**Comment by NickSwainston** [comment] 2023-04-04 08:25
> hi ,it seems that the log_parabolic_spectrum model cann't be adopted.

This is a separate problem, so please make a new issue

**Closed** 2023-04-04 08:25 UTC
Labels: bug
